backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: "latest"
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30014

  podAnnotations:    
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

  nameOverride: customer
  fullnameOverride: customer
  
  databaseConnectionUrl: "jdbc:postgresql://postgres:5432"
  databaseName: customer
  
  ingress:
    enabled: false

  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret

  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml

  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30000/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"
    - name: YAS_LOCATION_URL
      value: "http://location"
    - name: SPRING_APPLICATION_JSON
      value: '{"management":{"endpoints":{"web":{"exposure":{"include":"health,info,prometheus"}}}}}'

  metrics:
    enabled: true
  serviceMonitor:
    enabled: true