backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30010

  podAnnotations:    
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

  nameOverride: storefront-bff
  fullnameOverride: storefront-bff

  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,storefront-bff-extra-configmap"

  ingress:
    enabled: false

  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: storefront-bff-extra-config
      configMap:
        name: storefront-bff-extra-configmap

  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: storefront-bff-extra-config
      mountPath: /opt/yas/extra-config

  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/storefront-bff-extra-config.yaml

  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret

  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: "http://storefront-ui:3000"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30016/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
      value: "http://yas.local.com:30016/realms/Yas/protocol/openid-connect/auth"
    - name: SERVER_FORWARD_HEADERS_STRATEGY
      value: "framework"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/token"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/userinfo"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI
      value: "http://yas.local.com:30016/login/oauth2/code/keycloak"
    - name: NEXT_PUBLIC_AUTH_SERVER_URL
      value: "http://yas.local.com:30016/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
      value: "http://yas.local.com:80/realms/Yas"
    - name: YAS_SERVICES_PRODUCT
      value: "http://product:80"
    - name: YAS_SERVICES_CART
      value: "http://cart:80"
    - name: YAS_SERVICES_CUSTOMER
      value: "http://customer:80"
    - name: YAS_SERVICES_ORDER
      value: "http://order:80"
    - name: YAS_SERVICES_LOCATION
      value: "http://location:80"
    - name: YAS_SERVICES_INVENTORY
      value: "http://inventory:80"
    - name: YAS_SERVICES_TAX
      value: "http://tax:80"
    - name: YAS_SERVICES_MEDIA
      value: "http://media:80"
    - name: SPRING_APPLICATION_JSON
      value: '{"management":{"endpoints":{"web":{"exposure":{"include":"health,info,prometheus"}}}}}'

  metrics:
    enabled: true
  serviceMonitor:
    enabled: true