backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    nodePort: 30010

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

  nameOverride: storefront-bff
  fullnameOverride: storefront-bff

  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,storefront-bff-extra-configmap"

  ingress:
    enabled: false

  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: storefront-bff-extra-config
      configMap:
        name: storefront-bff-extra-configmap
  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: storefront-bff-extra-config
      mountPath: /opt/yas/extra-config
  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/storefront-bff-extra-config.yaml

  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret

  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://storefront-ui:3000
        
    # 1. ÉP SPRING BOOT PHẢI NHẬN DIỆN ĐÚNG CỔNG PHÍA SAU NGINX
    - name: SERVER_FORWARD_HEADERS_STRATEGY
      value: framework

    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30000/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"

    # Luồng bẻ lái giao diện đăng nhập cho trình duyệt (Dùng domain ngoài)
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
      value: "http://yas.local.com:30000/realms/Yas/protocol/openid-connect/auth"

    # 2. ÉP BFF ĐỔI TOKEN VÀ USERINFO QUA MẠNG NỘI BỘ K8S CỔNG 80 (TRÁNH LỖI DNS)
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/token"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/userinfo"

    # Dàn danh bạ microservices của anh em mình
    - name: YAS_SERVICES_PRODUCT
      value: http://product
    - name: YAS_SERVICES_CART
      value: http://cart
    - name: YAS_SERVICES_CUSTOMER
      value: http://customer
    - name: YAS_SERVICES_ORDER
      value: http://order
    - name: YAS_SERVICES_LOCATION
      value: http://location
    - name: YAS_SERVICES_INVENTORY
      value: http://inventory
    - name: YAS_SERVICES_TAX
      value: http://tax
    - name: YAS_SERVICES_MEDIA
      value: http://media