extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://storefront-ui:3000
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30000/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"

    # 🚀 DÒNG CHỐT HẠ: Ép con BFF phải điều hướng trình duyệt sang domain ngoài khi Đăng nhập
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
      value: "http://yas.local.com:30000/realms/Yas/protocol/openid-connect/auth"

    # Dàn danh bạ microservices hôm nọ anh em mình thêm
    - name: YAS_SERVICES_PRODUCT
      value: http://product
    - name: YAS_SERVICES_CART
      value: http://cart
    - name: YAS_SERVICES_CUSTOMER
      value: http://customer
    - name: YAS_SERVICES_ORDER
      value: http://order
    - name: YAS_SERVICES_LOCATION
      value: http://location
    - name: YAS_SERVICES_INVENTORY
      value: http://inventory
    - name: YAS_SERVICES_TAX
      value: http://tax
    - name: YAS_SERVICES_MEDIA
      value: http://media