hostname: yas.local.com
grafana:
  username: admin
  password: admin
postgresql:
  url: postgres-postgresql.yas-dev:5432  
  username: postgres
  password: admin

grafanaSpec:
  service:
    type: NodePort
    nodePort: 30018