hostname: yas.local.com
grafana:
  username: admin
  password: admin
postgresql:
  url: postgres-postgresql.yas-dev:5432  
  username: postgres
  password: admin

grafanaDeployment:
  spec:
    replicas: 1
grafanaService:
  spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30018