replicaCount: 1

image:
  repository: swaggerapi/swagger-ui
  pullPolicy: IfNotPresent
  tag: "v4.16.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "false"

podSecurityContext: {}

securityContext: {}

baseUrl: /
urls: |
  [
    { "url": "http://product:80/v3/api-docs", "name": "Product" },
    { "url": "http://media:80/v3/api-docs", "name": "Media" },
    { "url": "http://customer:80/v3/api-docs", "name": "Customer" },
    { "url": "http://cart:80/v3/api-docs", "name": "Cart" },
    { "url": "http://order:80/v3/api-docs", "name": "Order" },
    { "url": "http://location:80/v3/api-docs", "name": "Location" },
    { "url": "http://inventory:80/v3/api-docs", "name": "Inventory" },
    { "url": "http://tax:80/v3/api-docs", "name": "Tax" },
    { "url": "http://search:80/v3/api-docs", "name": "Search" }
  ]

service:
  type: NodePort      
  port: 80            
  targetPort: 80      
  nodePort: 30012     

# Chỗ mới thêm vào nằm ở đây nhe bro:
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

ingress:
  enabled: false      
  className: "nginx"
  host: api.yas.local.com
  annotations: {}
  hosts:
    - host: api.yas.local.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}