spring:
  #  PHẦN 1: BẢO MẬT KEYCLOAK (ĐÃ THÊM CỔNG :8080 NỘI BỘ CHUẨN)
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity:8080/realms/Yas
            authorization-uri: http://identity:8080/realms/Yas/protocol/openid-connect/auth
            token-uri: http://identity:8080/realms/Yas/protocol/openid-connect/token
            user-info-uri: http://identity:8080/realms/Yas/protocol/openid-connect/userinfo
            jwk-set-uri: http://identity:8080/realms/Yas/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://identity:8080/realms/Yas

  #  PHẦN 2: PHÂN LUỒNG MẠNG GATEWAY 
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - SaveSession
          routes:
            - id: product
              uri: http://product
              predicates:
                - Path=/api/product/**
              filters:
                - StripPrefix=1
            - id: cart
              uri: http://cart
              predicates:
                - Path=/api/cart/**
              filters:
                - StripPrefix=1
            - id: customer
              uri: http://customer
              predicates:
                - Path=/api/customer/**
              filters:
                - StripPrefix=1
            - id: order
              uri: http://order
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=1
            - id: inventory
              uri: http://inventory
              predicates:
                - Path=/api/inventory/**
              filters:
                - StripPrefix=1
            - id: media
              uri: http://media
              predicates:
                - Path=/api/media/**
              filters:
                - StripPrefix=1
            - id: search
              uri: http://search
              predicates:
                - Path=/api/search/**
              filters:
                - StripPrefix=1
            - id: tax
              uri: http://tax
              predicates:
                - Path=/api/tax/**
              filters:
                - StripPrefix=1
            - id: promotion
              uri: http://promotion
              predicates:
                - Path=/api/promotion/**
              filters:
                - StripPrefix=1
            # ĐÓN LÕNG CUỐI CÙNG CHO NEXTJS UI
            - id: nextjs
              uri: http://storefront-ui:3000
              predicates:
                - Path=/**