backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    nodePort: 30004

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

  nameOverride: search
  fullnameOverride: search
  
  databaseConnectionUrl: "jdbc:postgresql://postgres:5432"
  databaseName: search
  
  ingress:
    enabled: false

  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml

  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30000/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"
    - name: YAS_LOCATION_URL
      value: "http://location"

  metrics:
    enabled: false
  serviceMonitor:
    enabled: false