credentials:
  postgresql:
    username: postgres 
    password: admin
  elasticsearch:
    username: yas
    password: LarUmB3A49NTg9YmgW4=
  keycloak:
    backofficeBffClientSecret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF
    storefrontBffClientSecret: ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn
    customerManagementClientSecret: NKAr3rnjwm9jlakgKpelukZGFaHYqIWE
  redis:
    password: redis
  openai:
    apiKey: update-me

# Cấu hình application.yaml dùng chung cho 19 microservices
applicationConfig:
  spring:
    datasource:
      # URL cụ thể sẽ được đè bởi file deployment.yaml của từng service
      url: jdbc:postgresql://postgres-postgresql:5432/
      username: ${POSTGRESQL_USERNAME}
      password: ${POSTGRESQL_PASSWORD}
    kafka:
      bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://identity.yas.local.com/realms/Yas

  yas:
    services:
      cart: http://cart/cart
      customer: http://customer/customer
      inventory: http://inventory/inventory
      location: http://location/location
      media: http://media/media
      order: http://order/order
      payment: http://payment/payment
      payment-paypal: http://payment-paypal/payment-paypal
      product: http://product/product
      promotion: http://promotion/promotion
      rating: http://rating/rating
      search: http://search/search
      tax: http://tax/tax
      sampledata: http://sampledata/sampledata
      recommendation: http://recommendation/recommendation
      delivery: http://delivery/delivery
      webhook: http://webhook/webhook

# Cấu hình Sample Data
sampledataApplicationConfig:
  spring:
    datasource:
      product:
        url: jdbc:postgresql://postgres-postgresql:5432/product
      media:
        url: jdbc:postgresql://postgres-postgresql:5432/media

