credentials:
  postgresql:
    username: "postgres"
    password: "admin"
  elasticsearch:
    username: "yas"
    password: "LarUmB3A49NTg9YmgW4="
  keycloak:
    backofficeBffClientSecret: "TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF"
    storefrontBffClientSecret: "ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn"
    customerManagementClientSecret: "NKAr3rnjwm9jlakgKpelukZGFaHYqIWE"
  redis:
    password: "redis"
  openai:
    apiKey: "update-me"

# CỰC KỲ QUAN TRỌNG: Phải có dấu | ở đây
applicationConfig: |
  server:
    shutdown: "graceful"
    port: "80"
  management:
    otlp:
      tracing:
        endpoint: "http://opentelemetry-collector.observability:4318/v1/traces"
    server:
      port: "8090"
    health:
      readinessstate:
        enabled: "true"
      livenessstate:
        enabled: "true"
    tracing:
      sampling:
        probability: "1.0"
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: "http://identity.yas.local.com/realms/Yas"
    datasource:
      url: "jdbc:postgresql://postgres-postgresql:5432/"
      username: "${POSTGRESQL_USERNAME}"
      password: "${POSTGRESQL_PASSWORD}"
    kafka:
      bootstrap-servers: "kafka-cluster-kafka-brokers.kafka:9092"
  yas:
    services:
      cart: "http://cart/cart"
      customer: "http://customer/customer"
      inventory: "http://inventory/inventory"
      location: "http://location/location"
      media: "http://media/media"
      order: "http://order/order"
      payment: "http://payment/payment"
      product: "http://product/product"
      promotion: "http://promotion/promotion"
      rating: "http://rating/rating"
      search: "http://search/search"
      tax: "http://tax/tax"
      delivery: "http://delivery/delivery"
      webhook: "http://webhook/webhook"

# Cấu hình Sample Data cũng cần dấu |
sampledataApplicationConfig: |
  spring:
    datasource:
      product:
        url: "jdbc:postgresql://postgres-postgresql:5432/product"
      media:
        url: "jdbc:postgresql://postgres-postgresql:5432/media"

# Giữ nguyên cấu hình reloader
reloader:
  nameOverride: "yas-reloader"
  fullnameOverride: "yas-reloader"
  reloader:
    watchGlobally: false