backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: rating
  fullnameOverride: rating
  
  databaseName: rating
  
  ingress:
    enabled: false