backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: webhook
  fullnameOverride: webhook
  
  databaseName: webhook
  
  ingress:
    enabled: false