apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: yas-dev
  labels:
    dashboards: "grafana"
spec:
  client:
    preferDirectProxy: true
  deployment:
    spec:
      replicas: 1