ui:
  image:
    repository: ghcr.io/nashtech-garage/yas-storefront
    tag: latest
    pullPolicy: IfNotPresent

nameOverride: storefront-ui
fullnameOverride: storefront-ui

service:
  type: NodePort
  port: 80
  nodePort: 30016

ingress:
  enabled: false

extraEnvs:
  - name: API_BASE_PATH
    value: "http://yas.cloud.com:30010"