ui:
  image:
    repository: 23127206/yas-storefront-ui 
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: storefront-ui
  fullnameOverride: storefront-ui

  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront.yas.local.com/api

  ingress:
    enabled: false 