ui:
  image:
    repository: 23127206/storefront-ui
    tag: latest
    pullPolicy: Always  

  service:
    type: ClusterIP
    port: 3000          

  extraEnvs:
    - name: API_BASE_PATH
      value: "http://storefront-bff:80"

nameOverride: storefront-ui
fullnameOverride: storefront-ui

ingress:
  enabled: false