backend:
  image:
    repository: 23127206/yas-identity
    tag: latest
  service:
    type: NodePort
    port: 8080
    nodePort: 30000
extraEnvVars:
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "admin"