ui:
  image:
    repository: 23127206/backoffice-ui
    tag: latest
    pullPolicy: Always  

  service:
    type: ClusterIP
    port: 3000

nameOverride: backoffice-ui
fullnameOverride: backoffice-ui

ingress:
  enabled: false