backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: location
  fullnameOverride: location
  
  databaseName: location
  
  ingress:
    enabled: false