backend:
  image:
    repository: 23127206/yas-all-in-one
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30002

  podAnnotations:    
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

  nameOverride: order
  fullnameOverride: order
  
  databaseConnectionUrl: "jdbc:postgresql://postgres:5432"
  databaseName: order
  
  ingress:
    enabled: false

  extraVolumes:
    - name: order-application-config
      configMap:
        name: order-application-configmap
  extraVolumeMounts:
    - name: order-application-config
      mountPath: /opt/yas/order
  extraApplicationConfigPaths:
    - /opt/yas/order/order-application.yaml

  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "http://yas.local.com:30000/realms/Yas"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
      value: "http://identity:80/realms/Yas/protocol/openid-connect/certs"
    - name: YAS_LOCATION_URL
      value: "http://location"
    - name: SPRING_APPLICATION_JSON
      value: '{"management":{"endpoints":{"web":{"exposure":{"include":"health,info,prometheus"}}}}}'

  metrics:
    enabled: true
  serviceMonitor:
    enabled: true